import { readable } from "svelte/store"

const TeslaStore = readable([
  {
    id: 1,
    group: "Model S",
    label: "Long Range",
    value: "Long Range",
    price: 72990,
    image: "",
  },
  {
    id: 2,
    group: "Model S",
    label: "Plaid",
    value: "Plaid",
    price: 112990,
    image: "",
  },
  {
    id: 3,
    group: "Model S",
    label: "Plaid+",
    value: "Plaid+",
    price: 132990,
    image: "",
  },
  {
    id: 4,
    group: "Model 3",
    label: "Standard Range Plus",
    value: "Standard Range Plus",
    price: 30190,
    image: "",
  },
  {
    id: 5,
    group: "Model 3",
    label: "Long Range",
    value: "Long Range1",
    price: 39190,
    image: "",
  },
  {
    id: 6,
    group: "Model 3",
    label: "Performance",
    value: "Performance",
    price: 47190,
    image: "",
  },
  {
    id: 7,
    group: "Model X",
    label: "Long Range",
    value: "Long Range2",
    price: 83190,
    image: "",
  },
  {
    id: 8,
    group: "Model X",
    label: "Plaid",
    value: "Plaid2",
    price: 113190,
    image: "",
  },
  {
    id: 9,
    group: "Model Y",
    label: "Standard Range",
    value: "Standard Range",
    price: 34190,
    image: "",
  },
  {
    id: 10,
    group: "Model Y",
    label: "Long Range",
    value: "Long Range3",
    price: 42190,
    image: "",
  },
  {
    id: 11,
    group: "Model Y",
    label: "Performance",
    value: "Performance3",
    price: 52190,
    image: "",
  },
])

export default TeslaStore
